"""
Email connector — SMTP for incident reports, post-mortems, and scheduled digests.
Supports TLS/STARTTLS, Exchange, Gmail, and any SMTP relay.
"""
from __future__ import annotations

import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from connectors.base import BaseConnector, ConnectorConfig


class EmailConnector(BaseConnector):
    def __init__(self, config: ConnectorConfig) -> None:
        super().__init__(config)
        cfg = config.config
        self.host = cfg["host"]
        self.port = int(cfg.get("port", 587))
        self.username = cfg.get("username", "")
        self.password = cfg.get("password", "")
        self.from_email = cfg.get("from_email", self.username)

    async def test_connection(self) -> dict:
        try:
            context = ssl.create_default_context()
            with smtplib.SMTP(self.host, self.port, timeout=10) as server:
                server.ehlo()
                if self.port == 587:
                    server.starttls(context=context)
                if self.username:
                    server.login(self.username, self.password)
            return {"healthy": True}
        except Exception as e:
            return {"healthy": False, "error": str(e)}

    async def send_notification(self, message: str, channel: str = "", **kwargs) -> dict:
        """channel = recipient email address."""
        to_email = channel or kwargs.get("to", "")
        if not to_email:
            return {"ok": False, "error": "No recipient email provided"}

        subject = kwargs.get("subject", "OpsBrain Notification")
        return await self.send_email(to_email, subject, message)

    async def send_email(self, to: str, subject: str, body: str, html: bool = False) -> dict:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.from_email
        msg["To"] = to
        mime_type = "html" if html else "plain"
        msg.attach(MIMEText(body, mime_type))

        try:
            context = ssl.create_default_context()
            with smtplib.SMTP(self.host, self.port, timeout=30) as server:
                server.ehlo()
                if self.port == 587:
                    server.starttls(context=context)
                if self.username:
                    server.login(self.username, self.password)
                server.sendmail(self.from_email, to, msg.as_string())
            return {"ok": True, "to": to, "subject": subject}
        except Exception as e:
            return {"ok": False, "error": str(e)}

    async def send_postmortem(self, to: str, incident_title: str, postmortem_md: str) -> dict:
        """Send a generated post-mortem as a formatted HTML email."""
        html = f"""
        <html><body style="font-family: sans-serif; color: #333; max-width: 800px; margin: auto;">
        <h2 style="color: #1a1a2e;">📄 Post-Mortem: {incident_title}</h2>
        <p style="color: #666; font-size: 12px;">Generated by OpsBrain AI</p>
        <hr/>
        <div style="white-space: pre-wrap; font-size: 14px; line-height: 1.6;">{postmortem_md}</div>
        <hr/>
        <p style="color: #999; font-size: 11px;">Sent by OpsBrain — AI-Native AIOps Platform</p>
        </body></html>
        """
        return await self.send_email(to, f"Post-Mortem: {incident_title}", html, html=True)
